# Generated by Django 4.0.2 on 2022-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_fooddiary_calories_fooddiary_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddiary',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
